Repository np-guard/vpc-network-config-synthesis, pull requests merged in 2024-02, with the labels that each got.

#96 added fatal error (#93)
  pkg/synth/acl.go
Labels: size/XS

#99 added unspecified endpoints warning (#88)
  cmd/vpcgen/main.go
  pkg/ir/unspecified.go
Labels: size/L

#102 Adding setup-go step for CodeQL to work with Go 1.21
  .github/workflows/codeql.yml
Labels: size/XS

#104 Fix makefile so it runs on Linux
  Makefile
  README.md
Labels: size/S

#106 Running golangci-lint action according to docs
  .github/workflows/golangci-lint.yml
Labels: size/S
