Repository np-guard/vpc-network-config-synthesis, pull requests merged in 2024-09, with the labels that each got.

#196 Bump models to v0.4.0, including required changes to Segment
  go.mod
  go.sum
  pkg/io/jsonio/unmarshal.go
Labels: size/S

#200 Fix protocols SG generation
  pkg/io/confio/acl.go
  pkg/io/confio/conversions.go
  pkg/io/confio/sg.go
  pkg/io/csvio/sg.go
  pkg/io/mdio/sg.go
  pkg/io/tfio/sg.go
  pkg/synth/sg.go
  test/data/sg_single_conn/conn_spec.json
  test/data/sg_single_conn/sg_expected.csv
  test/data/sg_single_conn/sg_expected.tf
Labels: size/L

#203 Convert `[]ir.SGRule` to `[]*ir.SGRule`
  pkg/io/confio/sg.go
  pkg/io/csvio/sg.go
  pkg/io/mdio/sg.go
  pkg/io/tfio/sg.go
  pkg/ir/sg.go
Labels: size/M

#207 Multi VPC synthesis
  README.md
  pkg/io/jsonio/unmarshal.go
  pkg/ir/spec.go
  pkg/synth/acl.go
  pkg/synth/sg.go
  test/data_for_testing_errors/externals/config_object.json
  test/data_for_testing_errors/externals/conn_spec.json
  test/error_test_list.go
Labels: size/XXL

#208 Use ptrs to `ir.ACLRule`
  README.md
  pkg/io/confio/acl.go
  pkg/io/csvio/acl.go
  pkg/io/mdio/acl.go
  pkg/io/tfio/acl.go
  pkg/ir/acl.go
  pkg/ir/packet.go
Labels: size/M
