Repository np-guard/vpc-network-config-synthesis, pull requests merged in 2024-03, with the labels that each got.

#107 Support CIDR segments (#51)
  cmd/vpcgen/main.go
  go.mod
  go.sum
  pkg/io/confio/read_defs.go
  pkg/io/jsonio/data_model.go
  pkg/io/jsonio/unmarshal.go
  pkg/ir/ip.go
  pkg/ir/spec.go
  pkg/ir/unspecified.go
  pkg/synth/acl.go
  spec_schema.json
  test/data/acl_cidr_segments/config_object.json
  test/data/acl_cidr_segments/conn_spec.json
  test/data/acl_cidr_segments/nacl_expected.csv
  test/data/acl_cidr_segments/nacl_expected.tf
  test/data/acl_cidr_segments/nacl_single_expected.csv
  test/data/acl_cidr_segments/nacl_single_expected.tf
  test/end_to_end_test.go
Labels: size/XXL

#112 fixed CGO_Enabled definition
  Makefile
Labels: size/XS

#115 modified `endpoint` to `resource`
  cmd/vpcgen/main.go
  pkg/io/jsonio/data_model.go
  pkg/io/jsonio/provenance.go
  pkg/io/jsonio/unmarshal.go
  pkg/io/jsonio/unmarshal_test.go
  pkg/ir/spec.go
  pkg/ir/unspecified.go
  pkg/synth/acl.go
  pkg/synth/sg.go
  spec_schema.json
  test/end_to_end_test.go
Labels: size/L

#116 Bump models to v0.3.0: move json spec out
  .github/workflows/golangci-lint.yml
  Makefile
  go.mod
  go.sum
  pkg/io/jsonio/data_model.go
  pkg/io/jsonio/provenance.go
  pkg/io/jsonio/unmarshal.go
  pkg/io/jsonio/unmarshal_test.go
  pkg/ir/spec.go
  spec_schema.json
Labels: size/XL
