Repository np-guard/vpc-network-config-synthesis, pull requests merged in 2025-01, with the labels that each got.

#249 Fix a bug SG optimization
  pkg/optimize/sg/ipCubesToRules.go
Labels: bug, size/M, optimization

#229 read nACLs
  pkg/io/confio/parse_acls.go
  pkg/io/confio/parse_sgs.go
  pkg/ir/acl.go
Labels: size/L, optimization

#231 nACL optimization - fix cmd
  README.md
  cmd/subcmds/optimize.go
  cmd/subcmds/optimizeACL.go
  pkg/optimize/acl/acl.go
Labels: size/M, optimization

#252 Bump golang.org/x/net from 0.26.0 to v0.33.0 to fix security issue
  go.mod
  go.sum
Labels: size/XS

#251 Improve nACL optimization
  go.mod
  go.sum
  pkg/optimize/acl/acl.go
  pkg/optimize/acl/anyCubesToRules.go
  pkg/optimize/acl/cubesToRules.go
  pkg/optimize/acl/icmpCubesToRules.go
  pkg/optimize/acl/reduceCubes.go
  pkg/optimize/acl/rulesToCubes.go
  pkg/optimize/acl/tcpudpCubesToRules.go
  pkg/optimize/common.go
  pkg/optimize/sg/ipCubesToRules.go
  pkg/optimize/sg/rulesToCubes.go
  test/data/optimize_acl2/config_object.json
  test/data/optimize_acl2/details.txt
  test/data/optimize_acl3/config_object.json
  test/data/optimize_acl3/details.txt
  test/data/optimize_acl4/config_object.json
  test/data/optimize_acl4/details.txt
  test/expected/optimize_acl2_tf/nacl_expected.tf
  test/expected/optimize_acl3_tf/nacl_expected.tf
  test/expected/optimize_acl4_tf/nacl_expected.tf
  test/main_test_list.go
Labels: size/XXL

#253 nACL optimization - use some of any protocol cubes
  pkg/optimize/acl/acl.go
  pkg/optimize/acl/anyCubesToRules.go
  pkg/optimize/acl/cubesToRules.go
  pkg/optimize/common.go
  pkg/optimize/sg/ipCubesToRules.go
  test/data/optimize_acl5/config_object.json
  test/data/optimize_acl5/details.txt
  test/expected/optimize_acl5_tf/nacl_expected.tf
  test/main_test_list.go
Labels: size/XXL

#254 SG Optimization - use all anyProtocol cubes
  pkg/optimize/sg/ipCubesToRules.go
  pkg/optimize/sg/sg.go
  test/data/optimize_sg2/config_object.json
  test/data/optimize_sg2/details.txt
  test/expected/optimize_sg2_tf/sg_expected.tf
  test/main_test_list.go
Labels: size/XXL

#256 a test for #248 example 1
  test/data/optimize_acl6_issue248_example1/config_object.json
  test/data/optimize_acl6_issue248_example1/details.txt
  test/main_test_list.go
Labels: size/XL
